# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1014, 869)
        self.label_show_image = QtWidgets.QLabel(Form)
        self.label_show_image.setGeometry(QtCore.QRect(10, 10, 991, 671))
        self.label_show_image.setFrameShape(QtWidgets.QFrame.Box)
        self.label_show_image.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_show_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_show_image.setObjectName("label_show_image")
        self.pushButton_z_up = QtWidgets.QPushButton(Form)
        self.pushButton_z_up.setGeometry(QtCore.QRect(10, 690, 112, 34))
        self.pushButton_z_up.setObjectName("pushButton_z_up")
        self.pushButton_z_down = QtWidgets.QPushButton(Form)
        self.pushButton_z_down.setGeometry(QtCore.QRect(10, 740, 112, 34))
        self.pushButton_z_down.setObjectName("pushButton_z_down")
        self.pushButton_x_up = QtWidgets.QPushButton(Form)
        self.pushButton_x_up.setGeometry(QtCore.QRect(140, 690, 112, 34))
        self.pushButton_x_up.setObjectName("pushButton_x_up")
        self.pushButton_x_down = QtWidgets.QPushButton(Form)
        self.pushButton_x_down.setGeometry(QtCore.QRect(140, 740, 112, 34))
        self.pushButton_x_down.setObjectName("pushButton_x_down")
        self.lineEdit_range = QtWidgets.QLineEdit(Form)
        self.lineEdit_range.setGeometry(QtCore.QRect(400, 710, 113, 31))
        self.lineEdit_range.setObjectName("lineEdit_range")
        self.pushButton_dis_up = QtWidgets.QPushButton(Form)
        self.pushButton_dis_up.setGeometry(QtCore.QRect(270, 690, 112, 34))
        self.pushButton_dis_up.setObjectName("pushButton_dis_up")
        self.pushButton_dis_down = QtWidgets.QPushButton(Form)
        self.pushButton_dis_down.setGeometry(QtCore.QRect(270, 740, 112, 34))
        self.pushButton_dis_down.setObjectName("pushButton_dis_down")
        self.pushButton_start = QtWidgets.QPushButton(Form)
        self.pushButton_start.setGeometry(QtCore.QRect(140, 810, 112, 34))
        self.pushButton_start.setObjectName("pushButton_start")

        self.retranslateUi(Form)
        self.pushButton_z_up.clicked.connect(Form.z_up_cao) # type: ignore
        self.pushButton_x_up.clicked.connect(Form.x_up_cao) # type: ignore
        self.pushButton_dis_up.clicked.connect(Form.dis_up_cao) # type: ignore
        self.pushButton_z_down.clicked.connect(Form.z_down_cao) # type: ignore
        self.pushButton_x_down.clicked.connect(Form.x_down_cao) # type: ignore
        self.pushButton_dis_down.clicked.connect(Form.dis_down_cao) # type: ignore
        self.pushButton_start.clicked.connect(Form.start_cao) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_show_image.setText(_translate("Form", "TextLabel"))
        self.pushButton_z_up.setText(_translate("Form", "z轴+"))
        self.pushButton_z_down.setText(_translate("Form", "z轴-"))
        self.pushButton_x_up.setText(_translate("Form", "x轴+"))
        self.pushButton_x_down.setText(_translate("Form", "x轴-"))
        self.pushButton_dis_up.setText(_translate("Form", "距离+"))
        self.pushButton_dis_down.setText(_translate("Form", "距离-"))
        self.pushButton_start.setText(_translate("Form", "start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
